"use client";

import { useMemo, useState } from "react";
import { initialCampaign, quests, type Quest } from "../lib/quests";

type Scores = Record<string, number>;
const leaderboard = ["Nadia Permata", "Rizky Pratama", "Siti Nurhaliza", "Dimas Nugraha", "Ayu Lestari"];

export function GameHub() {
  const [name, setName] = useState("");
  const [started, setStarted] = useState(false);
  const [scores, setScores] = useState<Scores>({});
  const [activeQuest, setActiveQuest] = useState<Quest | null>(null);
  const [tab, setTab] = useState("Misi Saat Ini");
  const completed = Object.keys(scores).length;
  const score = Object.values(scores).reduce((a, b) => a + b, 0);
  const max = quests.reduce((a, q) => a + q.maxScore, 0);
  const nextQuest = quests.find((q) => !scores[q.id]);
  if (!started) return <Identity onEnter={(value) => { setName(value); setStarted(true); }} />;
  if (activeQuest) return <QuestPlay quest={activeQuest} index={quests.indexOf(activeQuest)} total={quests.length} onDone={(points) => { setScores((s) => ({ ...s, [activeQuest.id]: points })); setActiveQuest(null); }} />;
  return <main className="app-shell">
    <Topbar /><section className="hero"><div><p className="eyebrow">CAGEUR REKENING QUEST</p><h1>Wilujeng sumping,<br/><em>{name}!</em></h1><p>Siap bikin kebiasaan finansialmu makin cageur?</p></div><Mascot pose="👋" label="Kang Cageur menyapa" /></section>
    <section className="stat-grid"><Stat value={`${completed}/${quests.length}`} label="Quest selesai"/><Stat value={`${score}`} label={`Skor dari ${max}`}/><Stat value={`${completed}`} label="Badge terkumpul"/></section>
    <nav className="tabs">{["Misi Saat Ini", "Segera Hadir", "Riwayat Misi"].map((item) => <button className={tab === item ? "selected" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</nav>
    {tab === "Misi Saat Ini" ? <>
      <section className="campaign-card"><span className="campaign-icon">✦</span><div><p className="eyebrow">CAMPAIGN AKTIF · {initialCampaign.code}</p><h2>{initialCampaign.title}</h2><p>{initialCampaign.description}</p></div><div className="campaign-score"><b>{score}<small>/{max}</small></b><span>skor campaign</span></div></section>
      <div className="progress-label"><span>Progress misi</span><b>{completed} dari {quests.length} quest selesai</b></div><div className="progress"><i style={{ width: `${(completed / quests.length) * 100}%` }}/></div>
      <div className="quest-list">{quests.map((q, i) => <QuestCard quest={q} index={i} completed={scores[q.id]} locked={i > completed} onPlay={() => setActiveQuest(q)} key={q.id}/>)}</div>
      {completed === quests.length && <section className="finish"><span>🎉</span><div><b>MISI SELESAI!</b><p>Rekening cageur dimulai dari kebiasaan kecil.</p></div><button className="button gold">LIHAT HASIL</button></section>}
      <Leaderboard score={score}/>
    </> : <EmptyState tab={tab} />}
    <footer>Tong hilap, keuangan sehat dimulai dari kebiasaan kecil yang dilakukan konsisten. <b>Hayu, makin cageur rekeningna!</b></footer>
  </main>;
}

function Identity({ onEnter }: { onEnter: (name: string) => void }) { const [name, setName] = useState(""); const [nip, setNip] = useState(""); const [consent, setConsent] = useState(false); const [error, setError] = useState(""); return <main className="identity app-shell"><Topbar/><div className="identity-art"><Mascot pose="📋" label="Kang Cageur dengan clipboard"/><span className="coin c1">Rp</span><span className="coin c2">✦</span></div><p className="eyebrow">CAGEUR REKENING QUEST</p><h1>SAMPURASUN! <span>👋</span></h1><h2>Kenalan dulu sebelum masuk ke misi.</h2><p className="intro">Wilujeng sumping! Isi data singkat berikut supaya progres, skor, badge, dan ranking kamu bisa tercatat.</p><form onSubmit={(e) => { e.preventDefault(); if (name.trim().replace(/\s+/g, " ").length < 3 || !/[a-zA-Z]/.test(name) || !/^\d+$/.test(nip) || !consent) return setError("Data belum sesuai. Cek deui nama dan NIP-nya, ya."); onEnter(name.trim().replace(/\s+/g, " ")); }}><label>Nama Lengkap<input placeholder="Masukkan nama lengkap" value={name} onChange={(e) => setName(e.target.value)}/></label><label>NIP<input inputMode="numeric" placeholder="Masukkan NIP" value={nip} onChange={(e) => setNip(e.target.value)}/><small>Silakan isi 00000 untuk pegawai non-organik/swakelola.</small></label><label className="check"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)}/><span>Saya memahami bahwa data digunakan untuk validasi partisipasi dan pencatatan progres permainan.</span></label>{error && <p className="error">{error}</p>}<button className="button" type="submit">MASUK KE GAME HUB <span>→</span></button></form><p className="privacy">Data nama dan NIP hanya digunakan untuk validasi partisipasi, penyimpanan progres, dan pencatatan skor.</p></main> }
function Topbar() { return <header><span className="brand-mark">C</span><b>BUDAYA<br/>KERJA</b><span className="sound">♬</span></header> }
function Mascot({ pose, label }: { pose: string; label: string }) { return <div className="mascot" aria-label={label}><div className="iket">✦</div><div className="face">•‿•</div><div className="body"><span>{pose}</span></div></div> }
function Stat({ value, label }: { value: string; label: string }) { return <div className="stat"><b>{value}</b><span>{label}</span></div> }
function QuestCard({ quest, index, completed, locked, onPlay }: { quest: Quest; index: number; completed?: number; locked: boolean; onPlay: () => void }) { return <article className={`quest-card ${locked ? "locked" : ""}`}><span className="quest-number">{String(index + 1).padStart(2,"0")}</span><span className="quest-icon">{completed ? "✓" : locked ? "⌑" : quest.icon}</span><div><h3>{quest.title}</h3><p>{completed !== undefined ? `${completed}/${quest.maxScore} poin · Badge ${quest.badge}` : locked ? "Selesaikan misi sebelumnya" : quest.subtitle}</p></div>{completed !== undefined ? <b className="done">SELESAI</b> : <button className="small-button" disabled={locked} onClick={onPlay}>{locked ? "TERKUNCI" : "MULAI"}</button>}</article> }
function Leaderboard({ score }: { score: number }) { return <section className="leaderboard"><div className="section-title"><div><p className="eyebrow">KLASEMEN CAMPAIGN SAAT INI</p><h2>Siapa yang paling cageur?</h2></div><span className="podium">♕</span></div>{leaderboard.map((person, i) => <div className="rank" key={person}><b>#{i + 1}</b><span className="avatar">{person[0]}</span><span>{person}</span><strong>{100 - i * 4}</strong></div>)}<p className="your-rank">Posisi kamu saat ini: <b>#{score ? 6 : "—"}</b> dari 48 peserta.</p><button className="outline">LIHAT KLASEMEN LENGKAP</button></section> }
function EmptyState({ tab }: { tab: string }) { return <section className="empty"><span>{tab === "Segera Hadir" ? "🗓️" : "🏅"}</span><h2>{tab === "Segera Hadir" ? "Investasi Anti FOMO" : "Belum ada riwayat misi"}</h2><p>{tab === "Segera Hadir" ? "Segera hadir September 2026. Siapkan rekening yang makin cageur!" : "Campaign yang sudah diarsipkan dan pernah kamu ikuti akan tampil di sini."}</p></section> }

function QuestPlay({ quest, index, total, onDone }: { quest: Quest; index: number; total: number; onDone: (points: number) => void }) { const [selection, setSelection] = useState<string[]>([]); const [budget, setBudget] = useState([45,20,25,10]); const config = quest.config as any; const submit = () => { let points = quest.maxScore; if (quest.type === "tap_select") { const correct = config.choices.filter((x: any) => x.healthy).map((x:any)=>x.label); points = Math.round(quest.maxScore * selection.filter((x) => correct.includes(x)).length / correct.length); } if (quest.type === "budget_slider") points = Math.max(4, quest.maxScore - budget.reduce((sum, n, i) => sum + Math.abs(n - config.categories[i].ideal), 0)); onDone(points); }; return <main className="app-shell play"><Topbar/><button className="back" onClick={() => onDone(0)}>← Kembali ke misi</button><p className="eyebrow">QUEST {index + 1} DARI {total}</p><h1>{quest.title}</h1><p className="instruction">{config.instruction}</p><div className="game-panel">{quest.type === "tap_select" && <div className="choices">{config.choices.map((c: any) => <button className={selection.includes(c.label) ? (c.healthy ? "correct" : "wrong") : ""} onClick={() => !selection.includes(c.label) && setSelection([...selection,c.label])} key={c.label}>{c.label}<span>{selection.includes(c.label) ? (c.healthy ? "✓" : "!") : "+"}</span></button>)}</div>}{quest.type === "hidden_object" && <Hunt targets={config.targets} decoys={config.decoys}/>} {quest.type === "budget_slider" && <div className="budget">{config.categories.map((c:any, i:number) => <label key={c.label}><span>{c.label}<b>{budget[i]} koin</b></span><input type="range" min="0" max="100" value={budget[i]} onChange={(e) => setBudget(budget.map((n:number,j:number) => j === i ? Number(e.target.value) : n))}/></label>)}<div className="total-coins">TOTAL <b>{budget.reduce((a:number,b:number)=>a+b,0)}</b> / 100 koin</div></div>}{quest.type === "swipe_cards" && <Swipe items={config.items}/>}</div><button className="button" onClick={submit}>SELESAIKAN QUEST <span>→</span></button></main> }
function Hunt({ targets, decoys }: { targets: string[]; decoys: string[] }) { const [hit, setHit] = useState<string[]>([]); return <><div className="timer">⏱ 00:30 <b>{hit.length}/{targets.length} ditemukan</b></div><div className="hunt">{[...targets,...decoys].map(x => <button className={hit.includes(x) ? "found" : ""} onClick={() => targets.includes(x) && setHit([...hit,x])} key={x}>{hit.includes(x) ? "✓ " : ""}{x}</button>)}</div></> }
function Swipe({ items }: { items: {label:string;best:string}[] }) { const [at, setAt] = useState(0); const item = items[at]; return <div className="swipe"><p className="card-count">{items.length - at} kartu tersisa</p>{item ? <><div className="swipe-card"><span>🛍️</span><h2>{item.label}</h2><p>Keputusan paling bijak?</p></div><div className="swipe-actions">{["Keluarkan", "Tunda 24 Jam", "Checkout"].map(x => <button onClick={() => setAt(at+1)} key={x}>{x}</button>)}</div></> : <p className="nice">NICE! Semua kartu sudah dipilih.</p>}</div> }
